info:
  profile: prod

name: Paul
words: 'God bless us and everybody'

food: '{cipher}081a82751e574eb14f7f7715ac6f8316cd0a229655ce7187e710f579fc947c19'


#功能开关 - 开启/关闭注册功能
userservice:
  registration:
    disabled: true
  
